#pragma once
#ifndef BLE_CHARACTERISTICS
#define BLE_CHARACTERISTICS

const char* SERVICE_UUID = "YOUR GENERATED SERVICE_UUID HERE";
const char* CHARACTERISTIC_UUID = "YOUR CHARACTERISTIC_UUID HERE";
const char* BLE_SERVERNAME = "Moba BLE Remote";

#endif